// Demo data for when user is in demo mode (no database connection)

import type { Lead, Client, Activity, Quote, Invoice, Region, Profile, InventoryItem, Document } from '@/types/database';

export const demoRegions: Region[] = [
  { id: 'region-1', name: 'Bratislavský kraj', created_at: new Date().toISOString() },
  { id: 'region-2', name: 'Trnavský kraj', created_at: new Date().toISOString() },
  { id: 'region-3', name: 'Nitriansky kraj', created_at: new Date().toISOString() },
  { id: 'region-4', name: 'Trenčiansky kraj', created_at: new Date().toISOString() },
  { id: 'region-5', name: 'Žilinský kraj', created_at: new Date().toISOString() },
];

export const demoProfiles: Profile[] = [
  {
    id: 'admin-1',
    email: 'admin@artstone.sk',
    full_name: 'Peter Admin',
    role: 'admin',
    phone: null,
    region_id: null,
    avatar_url: null,
    theme_preference: 'system',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'manager-1',
    email: 'manager@artstone.sk',
    full_name: 'Jana Manažérová',
    role: 'manager',
    phone: null,
    region_id: 'region-1',
    avatar_url: null,
    theme_preference: 'system',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sales-1',
    email: 'sales@artstone.sk',
    full_name: 'Marek Obchodník',
    role: 'sales',
    phone: null,
    region_id: 'region-1',
    avatar_url: null,
    theme_preference: 'system',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sales-2',
    email: 'lucia@artstone.sk',
    full_name: 'Lucia Nováková',
    role: 'sales',
    phone: null,
    region_id: 'region-2',
    avatar_url: null,
    theme_preference: 'system',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sales-3',
    email: 'martin@artstone.sk',
    full_name: 'Martin Kováč',
    role: 'sales',
    phone: null,
    region_id: 'region-3',
    avatar_url: null,
    theme_preference: 'system',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];


export const demoLeads: Lead[] = [
  {
    id: 'lead-1',
    contact_name: 'Ján Novák',
    company_name: 'Novák s.r.o.',
    email: 'jan.novak@example.com',
    phone: '+421 900 111 222',
    address: 'Hlavná 123',
    postal_code: '81101',
    region_id: 'region-1',
    status: 'new',
    source_type: 'facebook_lead_ads',
    source_campaign: 'Summer 2024',
    source_adset: null,
    source_ad: null,
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'summer2024',
    external_lead_id: null,
    assigned_user_id: null,
    duplicate_of_lead_id: null,
    converted_to_client_id: null,
    notes: 'Záujem o kamenné obklady',
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lead-2',
    contact_name: 'Mária Kováčová',
    company_name: null,
    email: 'maria.kovacova@email.sk',
    phone: '+421 900 333 444',
    address: 'Dunajská 45',
    postal_code: '81108',
    region_id: 'region-1',
    status: 'contacted',
    source_type: 'google_ads',
    source_campaign: 'Brand 2024',
    source_adset: null,
    source_ad: null,
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'brand',
    external_lead_id: null,
    assigned_user_id: 'sales-1',
    duplicate_of_lead_id: null,
    converted_to_client_id: null,
    notes: null,
    created_by: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'lead-3',
    contact_name: 'Peter Horváth',
    company_name: 'Horváth Stavby',
    email: 'peter@horvathstavby.sk',
    phone: '+421 900 555 666',
    address: 'Priemyselná 8',
    postal_code: '91701',
    region_id: 'region-2',
    status: 'offer',
    source_type: 'website_form',
    source_campaign: null,
    source_adset: null,
    source_ad: null,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    external_lead_id: null,
    assigned_user_id: 'sales-1',
    duplicate_of_lead_id: null,
    converted_to_client_id: null,
    notes: 'Veľký projekt - výstavba hotela',
    created_by: null,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'lead-4',
    contact_name: 'Eva Szabóová',
    company_name: 'ES Interiéry',
    email: 'eva@esinteriery.sk',
    phone: '+421 900 777 888',
    address: null,
    postal_code: null,
    region_id: 'region-3',
    status: 'won',
    source_type: 'manual',
    source_campaign: null,
    source_adset: null,
    source_ad: null,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    external_lead_id: null,
    assigned_user_id: 'sales-1',
    duplicate_of_lead_id: null,
    converted_to_client_id: 'client-1',
    notes: 'Konvertovaný na klienta',
    created_by: null,
    created_at: new Date(Date.now() - 604800000).toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString(),
  },
];

export const demoClients: Client[] = [
  {
    id: 'client-1',
    contact_name: 'Eva Szabóová',
    company_name: 'ES Interiéry',
    email: 'eva@esinteriery.sk',
    phone: '+421 900 777 888',
    address: 'Nábrežná 15',
    postal_code: '94901',
    region_id: 'region-3',
    status: 'active',
    assigned_user_id: 'sales-1',
    lead_origin_id: 'lead-4',
    total_value: 12500,
    notes: 'Pravidelný zákazník',
    created_by: null,
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'client-2',
    contact_name: 'Tomáš Baláž',
    company_name: 'Baláž Development',
    email: 'tomas@balazdevelopment.sk',
    phone: '+421 900 999 000',
    address: 'Stavbárska 22',
    postal_code: '82108',
    region_id: 'region-1',
    status: 'active',
    assigned_user_id: 'sales-1',
    lead_origin_id: null,
    total_value: 45000,
    notes: 'VIP klient',
    created_by: null,
    created_at: new Date(Date.now() - 2592000000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoActivities: Activity[] = [
  {
    id: 'activity-1',
    entity_type: 'lead',
    entity_id: 'lead-1',
    activity_type: 'call',
    title: 'Úvodný telefonát',
    description: 'Zákazník prejavil záujem o produkty',
    created_by: 'sales-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'activity-2',
    entity_type: 'lead',
    entity_id: 'lead-2',
    activity_type: 'email',
    title: 'Odoslaný katalóg',
    description: 'Odoslaný produktový katalóg emailom',
    created_by: 'sales-1',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'activity-3',
    entity_type: 'client',
    entity_id: 'client-1',
    activity_type: 'meeting',
    title: 'Osobné stretnutie',
    description: 'Stretnutie v showroome',
    created_by: 'sales-1',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const demoInventory: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Kamenný obklad Rustical',
    sku: 'KO-RUST-001',
    category_id: 'cat-1',
    qty_available: 150,
    qty_reserved: 20,
    min_stock: 50,
    purchase_price: 25,
    sale_price: 45,
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-2',
    name: 'Bridlicová dlažba Premium',
    sku: 'BD-PREM-002',
    category_id: 'cat-2',
    qty_available: 30,
    qty_reserved: 10,
    min_stock: 40,
    purchase_price: 35,
    sale_price: 65,
    notes: 'Nízky stav zásob!',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-3',
    name: 'Dekoratívny kameň White',
    sku: 'DK-WHT-003',
    category_id: 'cat-1',
    qty_available: 200,
    qty_reserved: 0,
    min_stock: 30,
    purchase_price: 18,
    sale_price: 32,
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoQuotes: Quote[] = [
  {
    id: 'quote-1',
    quote_number: 'CP-2024-0001',
    client_id: 'client-1',
    status: 'sent',
    valid_until: new Date(Date.now() + 2592000000).toISOString(),
    subtotal: 5000,
    discount: 0,
    shipping: 0,
    tax_rate: 20,
    tax_amount: 1000,
    total: 6000,
    notes: null,
    pdf_url: null,
    created_by: 'sales-1',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'quote-2',
    quote_number: 'CP-2024-0002',
    client_id: 'client-2',
    status: 'accepted',
    valid_until: new Date(Date.now() + 1728000000).toISOString(),
    subtotal: 15000,
    discount: 0,
    shipping: 0,
    tax_rate: 20,
    tax_amount: 3000,
    total: 18000,
    notes: 'Schválené vedením',
    pdf_url: null,
    created_by: 'sales-1',
    created_at: new Date(Date.now() - 604800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoInvoices: Invoice[] = [
  {
    id: 'invoice-1',
    invoice_number: 'FA-2024-0001',
    client_id: 'client-2',
    quote_id: 'quote-2',
    status: 'paid',
    issue_date: new Date(Date.now() - 604800000).toISOString(),
    due_date: new Date(Date.now() - 86400000).toISOString(),
    subtotal: 15000,
    tax_rate: 20,
    tax_amount: 3000,
    total: 18000,
    notes: null,
    pdf_url: null,
    created_by: 'admin-1',
    created_at: new Date(Date.now() - 604800000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoDocuments: Document[] = [
  {
    id: 'doc-1',
    title: 'Cenník 2024',
    category: 'pricelist',
    file_url: 'https://example.com/cennik2024.pdf',
    file_type: 'application/pdf',
    file_size: '2.5 MB',
    allowed_roles: ['admin', 'manager', 'sales'],
    allowed_user_ids: [],
    created_by: 'admin-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-2',
    title: 'Príručka pre obchodníkov',
    category: 'manual',
    file_url: 'https://example.com/manual.pdf',
    file_type: 'application/pdf',
    file_size: '5.1 MB',
    allowed_roles: ['admin', 'manager', 'sales'],
    allowed_user_ids: [],
    created_by: 'admin-1',
    created_at: new Date(Date.now() - 2592000000).toISOString(),
  },
];

export const demoDashboardStats = {
  leads: { total: 4, new: 1, contacted: 1, offer: 1, won: 1, newChange: 12 },
  clients: { total: 2, active: 2, activeChange: 8 },
  quotes: { total: 2, pending: 1, accepted: 1, totalValue: 24000, totalChange: -3 },
  invoices: { total: 1, paid: 1, overdue: 0, totalValue: 18000, paidValue: 18000 },
  salespeople: 3,
  lowStockItems: 1,
  conversionRate: 25,
  conversionChange: 5,
};

export const demoLeadsBySource = [
  { source: 'facebook_lead_ads', count: 1 },
  { source: 'google_ads', count: 1 },
  { source: 'website_form', count: 1 },
  { source: 'manual', count: 1 },
];

export const demoRegionStats = [
  { region: 'Bratislavský kraj', leads: 2, clients: 1 },
  { region: 'Trnavský kraj', leads: 1, clients: 0 },
  { region: 'Nitriansky kraj', leads: 1, clients: 1 },
];
